[package]
name = "calendar-caldav"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
sqlx.workspace = true
tracing.workspace = true
bytes.workspace = true
futures-util.workspace = true
http.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
thiserror.workspace = true
icalendar.workspace = true
dav-server.workspace = true
calendar-core = { path = "../calendar-core" }
calendar-db = { path = "../calendar-db" }

[dev-dependencies]
tokio.workspace = true
